### PR TITLE
Only glob up `.(c|m)?js` files

### LINKED ISSUE #30: ignore .DS_Store
`Error: Cannot run ".DS_Store" after "1661768058-init.cjs" has been applied`

maybe it can only grab `.js,.cjs` extensions

### PR DESCRIPTION
**Pull request by TehShrike**
I want to put a .sql file into my migrations directory :-x

Closes #30

### CODE REVIEW

File: lib/util.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ const { resolve } = require('path');
 exports.glob = async function (dir) {
 	const output = [];
 	await totalist(dir, (name, abs) => output.push({ name, abs }));
```
Comment (lukeed) [inline lib/util.js:7]: filter while pushing into collection & still allow typescript support
```suggestion
	await totalist(dir, (name, abs) => /\.[cm]?[tj]s$/.test(name) && output.push({ name, abs }));
```

File: lib/util.js [hunk 2]
```diff
@@ -5,7 +5,7 @@ const { resolve } = require('path');
...
-	return output.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric:true })); // ~rand order
+	return output.filter(({ name }) => /\.(c|m)?js$/.test(name)).sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric:true })); // ~rand order
```
Comment (lukeed) [inline lib/util.js:8]:
```suggestion
	return output.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric:true })); // ~rand order
```

**Review by lukeed — CHANGES_REQUESTED** [review]
